### ISSUE TITLE
MT7922 crash after 23–24 hours of operation when upstream AP disconnects

### ISSUE THREAD

**Issue by o4114o** [openwrt/mt76#1013]
Hi,

I am using the MT7922 Wi-Fi module in an OpenWrt 23.x environment and have encountered a reproducible crash after long-term operation in **Station + Access Point (STA + AP)** mode. Please suggest if there is a known fix for this STA + AP stability issue when the upstream AP disconnects after long uptime.

### **Summary of the issue**

* **Firmware used:** `WIFI_MT7922_patch_mcu_1_1_hdr.bin` and `WIFI_RAM_CODE_MT7922_1.bin` (Feb 20 2024 and Sept 2025 versions both tested)
* **Kernel/driver:** OpenWrt 23.x (mt76 driver)
* **Mode:** Single radio (radio0) operating simultaneously as STA uplink and AP for local clients

### **Steps to reproduce**

1. Configure radio0 as STA connecting to an upstream AP on channel (e.g. 161).
2. On the same radio, start AP mode with SSID “WR315B” on the same channel.
3. Let the system run continuously for **more than 23–24 hours**.
4. When the upstream AP disconnects (e.g. hotspot turned off or signal lost), the system outputs messages such as:

   ```
   phy0-sta0: Driver requested disconnection from AP 00:00:00:00:00:00
   mt7921e 0000:01:00.0: Message 00000010 (seq 8) timeout
   mt7921e 0000:01:00.0: Failed to get patch semaphore
   mt7921e 0000:01:00.0: chip reset failed
   ```
5. After this, the wireless interface (`phy0`) disappears; `wifi reload`, ‘/etc/init.d/network restart’, `rmmod/modprobe`, ‘reboot’ cannot recover it. The PCI bus show no module. Only a full hardware reboot restores the module.

**Observation and analysis**

* The failure appears after long-term operation (> 23 h) and is triggered by the STA disconnection event.
* Updating to the 2025-09 firmware does not solve the problem, suggesting a driver/firmware synchronization issue involving PCIe reset and MCU power state.
* Disabling power save (`iw dev phy0-sta0 set power_save off`) may delay the issue but does not prevent it.

**Comment by castiel652** [comment]
Can you try 24.10

**Comment by o4114o** [comment]
I have tried 24.10.3 and 24.10.4, but the issue still occurs. 
Attached is the system boot and the log when the problem occurred.

[log-OpenWrt 24.10.4.txt](https://github.com/user-attachments/files/23353346/log-OpenWrt.24.10.4.txt)

**Comment by castiel652** [comment]
Maybe mt7922 needs something like this too https://github.com/openwrt/mt76/commit/79dd14f2e8161b656341b6653261779199aedbe4

**Comment by zbowling** [comment]
my patch in https://github.com/openwrt/mt76/pull/1034 likely solves this. I've been fixing issues with MT7925, but that driver is based on this one and inherited many of the bugs.

**Comment by o4114o** [comment]
@zbowling After applying the patch in [#1034](https://github.com/openwrt/mt76/pull/1034) , the iwinfo command hangs and becomes unresponsive.

<img width="619" height="191" alt="Image" src="https://github.com/user-attachments/assets/10aeff3f-98da-4021-b56b-bd07355811be" />

**Comment by zbowling** [comment]
Will take a look

**Comment by zbowling** [comment]
> [@zbowling](https://github.com/zbowling) After applying the patch in [#1034](https://github.com/openwrt/mt76/pull/1034) , the iwinfo command hangs and becomes unresponsive.
> 

You are right. Thanks for testing my backport. I updated the patch.

The original patch added mutex protection around `mt7921_roc_abort_sync()` call sites in suspend paths, but those paths already had mutex protection. I missed that backporting. This created nested mutex acquisition (same mutex acquired twice), causing a deadlock since Linux mutexes aren't recursive.

The fix moves the mutex protection **inside** `mt7921_roc_abort_sync()` around the interface iteration where MCU functions are called, and removes it from the suspend call sites. This matches the pattern used in the MT7925 patches and prevents deadlocks.

**Before (deadlock):**
```c
// Suspend path already has mutex
mt792x_mutex_acquire(dev);
mt7921_roc_abort_sync(dev);  // Patch added mutex here = nested = deadlock
mt792x_mutex_release(dev);
```

**After (fixed):**
```c
// Inside mt7921_roc_abort_sync()
if (test_and_clear_bit(...)) {
    mt792x_mutex_acquire(dev);  // Mutex here, inside the function
    ieee80211_iterate_interfaces(...);
    mt792x_mutex_release(dev);
}

// Suspend path - no mutex needed
mt7921_roc_abort_sync(dev);  // Function handles mutex internally
```

**Comment by o4114o** [comment]
@zbowling Thank you for the update. However, I am still experiencing the same issue with the [5cf8e47](https://github.com/openwrt/mt76/pull/1034/commits/5cf8e4763a8ac4089049c9070cc2b7dab1c02010) patch. After the STA connects to the AP, iwinfo hangs.

**Comment by zbowling** [comment]
I'll try to investigate this week. I have that chipset now. I'm not using
openwrt right now but arch but should be close enough to try and repro.

Zac Bowling
