### ISSUE TITLE
mt7981/mt7986 sta connection to AP with AX mode fail

### ISSUE THREAD

**Issue by ptpt52** [openwrt/mt76#792]
```
7981 client STA(wds)----(broken connection)----7981 AP(wds) with AX
```

**Comment by ptpt52** [comment]
@nbd168 
confirmed this issue
and if use AP with AC mode the connection is good:

good:
```
7981 client STA(wds)----(broken connection)----7981 AP(wds) with AC
```

**Comment by soxrok2212** [comment]
Same issue as the following:

https://github.com/openwrt/openwrt/issues/12905
https://forum.openwrt.org/t/wireless-client-mode-broken-on-wax206-post-r22866/162406
https://forum.openwrt.org/t/mt7621-wds-with-channel-width-20-mhz-and-ax-not-working-in-newer-snapshots/161942

**Comment by cmonroe** [comment]
I think this [patch](https://protect-de.mimecast.com/s/iT8qCmqKZQuEGGoF9l_H6?domain=urldefense.com) should work around the problem you are running into.

Alternately, you could revert [4046b591](https://github.com/openwrt/mt76/commit/4046b59183234a503e8fb017549c6d66576e941d) for now.

The fix above has not made it into mt76 just yet.. it sounds like there's some discussion as to whether the proposed patch above is the ideal way to fix the issue or if it should be handled in mac80211.

**Comment by ptpt52** [comment]
@cmonroe  I would like to have this a try.

**Comment by zhaojh329** [comment]
> I think this [patch](https://pastebin.mozilla.org/qib2rh8Y/raw) should work around the problem you are running into.
> 
> Alternately, you could revert [4046b591](https://github.com/openwrt/mt76/commit/4046b59183234a503e8fb017549c6d66576e941d) for now.
> 
> The fix above has not made it into mt76 just yet.. it sounds like there's some discussion as to whether the proposed patch above is the ideal way to fix the issue or if it should be handled in mac80211.

Good. I tested. It works fine.

**Comment by cryobry** [comment]
I'm still having issues after latest merge with stability on WDS client and 802.11ax. Server seems to function fine, WDS on client works fine using 802.11ac 160mhz but with 802.11ax 160mhz it repeatedly drops the connection and gets locked into lower rates, etc. This is using a matched pair of AX6000's, MT7986.

**Comment by ptpt52** [comment]
@cryobry  I tested the mt76 latest code, and it looks good.

**Comment by soxrok2212** [comment]
Did either of you test with a VAP on the same radio? I'm still getting poor throughput when a radio has a VAP and a mesh node. May/may not be the same with WDS.

**Comment by cmonroe** [comment]
@cryobry I have a pair of 2G/6G MT7986 boards using 4mac client mode on the 6G interface of one on a 160MHz channel.. no issues with that. I will try a 5G 4mac client on MT7986 shortly.

@soxrok2212 I thought I saw an issue on a unit which has a 4mac STA (wireless uplink) and 4mac AP (downlink to another mesh node) but have not been able to reproduce it today. Does the problem change for you after reboot or power cycle?

**Comment by soxrok2212** [comment]
@cmonroe negative. Poor performance immediately after it boots.

**Comment by soxrok2212** [comment]
@nbd168 Seems like when 802.11s is enabled with other VAPs on the same radio, TX on the router gets limited to 20MHz for wireless clients only. Speeds reflect that:
```
xx:xx:xx:xx:xx:xx  -64 dBm / -92 dBm (SNR 28)  0 ms ago
	RX: 907.4 MBit/s, HE-MCS 9, 80MHz, HE-NSS 2, HE-GI 1, HE-DCM 0   1304942 Pkts.
	TX: 286.7 MBit/s, HE-MCS 11, 20MHz, HE-NSS 2, HE-GI 0, HE-DCM 0   1410962 Pkts.
	expected throughput: unknown
```

RX direction is fine, and this doesn't appear to affect the mesh node, only wireless clients.

**Comment by cryobry** [comment]
@ptpt52 Indeed, on latest snapshot WDS client has been steady for several hours for me on 160mhz AX. I will report back if there are issues. Thank you.

**Comment by Djfe** [comment]
this has likely been fixed by now, has it?

**Comment by knuxyl** [comment]
No I am still not able to get STA/client working with this SoC on AX. I didn't know it was related to it being AX but this is certainly still a problem

Edit on Jan 29 2026
Still doesn't work with OpenWRT 25.12 RC3. WiFi AC, AX, N, or any bandwidth, all the same result. It 99% of time sits at 6 Mbit/s receive at 20 MHz. Testing on a Banana Pi R3 Mini. I also had this problem on a Wavlink outdoor router that I have but I don't need that for STA and it's being used. I need the BPI-R3 mini to work as 5GHz STA.

<img width="653" height="114" alt="Image" src="https://github.com/user-attachments/assets/c08e4e33-5532-4897-ab9e-8147776ba9a2" />

kmod-mt76-core - 6.12.66.2025.11.06~eb567bc7-r2
mt7986-wo-firmware - 20251125-r1
kmod-mt7986-firmware - 6.12.66.2025.11.06~eb567bc7-r2
(idk what the strikethroughs are about)

**Comment by castiel652** [comment]
> Edit on Jan 29 2026 Still doesn't work with OpenWRT 25.12 RC3. WiFi AC, AX, N, or any bandwidth, all the same result. It 99% of time sits at 6 Mbit/s receive at 20 MHz. Testing on a Banana Pi R3 Mini.

@knuxyl 
Run a speedtest or iperf

**Comment by knuxyl** [comment]
> > Edit on Jan 29 2026 Still doesn't work with OpenWRT 25.12 RC3. WiFi AC, AX, N, or any bandwidth, all the same result. It 99% of time sits at 6 Mbit/s receive at 20 MHz. Testing on a Banana Pi R3 Mini.
> 
> [@knuxyl](https://github.com/knuxyl) Run a speedtest or iperf

It doesn't communicate at all. I can't communicate with the Access Point, so a speed test will do nothing.

**Comment by Djfe** [comment]
that might be a different issue related to powersaving and powersaving queues.
does the issue disappear when running `wifi`? (restarting wifi)

**Comment by Djfe** [comment]
An actual patch is being worked on, feel free to test this Workaround until then
https://github.com/freifunk-gluon/gluon/blob/main/patches/openwrt/0013-mt7915-detect-and-purge-stuck-PLE-queues.patch

**Comment by knuxyl** [comment]
@Djfe Restarting wifi doesn't fix it, I just tested. Since this start of the router it is showing like ~200Mbit connection. It's just feels better today? I don't know, it's still not working. 30 seconds later and now it's back down to 6Mbit.

@castiel652 im sorry i was wrong, i went back and tested it and it does have intermittent connection. i assumed it didn't because i could never get anything to load. here's an iperf (bpi r3 -> openwrt router)

> `iperf3 -c 192.168.1.1`
> Connecting to host 192.168.1.1, port 5201
> [  5] local 192.168.1.8 port 48632 connected to 192.168.1.1 port 5201
> [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
> [  5]   0.00-9.81   sec  0.00 Bytes  0.00 bits/sec    1   14.1 KBytes       
> [  5]   9.81-10.00  sec  0.00 Bytes  0.00 bits/sec    0   14.1 KBytes       
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-10.00  sec  0.00 Bytes  0.00 bits/sec    1            sender
> [  5]   0.00-11.89  sec  0.00 Bytes  0.00 bits/sec                  receiver

> `iperf3 -c 192.168.1.1 -t 10`
> Connecting to host 192.168.1.1, port 5201
> [  5] local 192.168.1.8 port 49142 connected to 192.168.1.1 port 5201
> [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
> [  5]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec    0   14.1 KBytes       
> [  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    0   14.1 KBytes       
> [  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
> [  5]   3.00-4.00   sec   256 KBytes  2.10 Mbits/sec    0   38.2 KBytes       
> [  5]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec    0   76.4 KBytes       
> [  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0   76.4 KBytes       
> [  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    0   76.4 KBytes       
> [  5]   7.00-8.00   sec   512 KBytes  4.19 Mbits/sec    1    129 KBytes       
> [  5]   8.00-9.00   sec   512 KBytes  4.19 Mbits/sec    0    257 KBytes       
> [  5]   9.00-10.00  sec   640 KBytes  5.24 Mbits/sec    0    373 KBytes       
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bitrate         Retr
> [  5]   0.00-10.00  sec  2.00 MBytes  1.68 Mbits/sec    2            sender
> [  5]   0.00-10.28  sec   768 KBytes   612 Kbits/sec                  receiver

**Comment by Djfe** [comment]
are you interested in building yourself an image with the workaround to test it? :)

**Comment by knuxyl** [comment]
> are you interested in building yourself an image with the workaround to test it? :)

yeah, i'm not sure if im going to do it today though. openwrt's build system is quite involved but i have experience with it. i read the docs and it should be easy to apply the patch with quilt. ill post back with results.

**Comment by Djfe** [comment]
the patch is currently made for the branch openwrt-24.10.x (in-case that helps with quilt)

**Comment by knuxyl** [comment]
it might be a little bit before i can get to testing this. too much going on atm and my build system is wack right now (gentoo). im keeping this in the back of my mind though, I want this to work because I have 2 useless routers that I can benefit from so I'll come back to this later.
